#! /bin/bash

# Daniel Hewlett
# Utility to backup directories and manage backup files
# Last Revision: 12/26/2018
# Name and purpose of top level variables:
# CONFIG_PATH specifies path to config file backup.conf
# CONFIG_TEXT contains text from config file, converted to runnable script
# BACKUP_ENTRIES_TEXT contains text for backup entries from config file
# BACKUP_ENTRIES_ARRAY containts backup entries split into an array

##print help text to the console

#iterate over all backup entries and parse them
parse_backup_entries() {
echo
echo "Parsing backup entries from config..."
for item in "${BACKUP_ENTRIES_ARRAY[@]}"
do	
	echo "BACKUP ENTRY: "$item""
	local BE_NAME=$(echo $item| cut -d: -f1)
	local BE_DIRECTORY=$(echo $item| cut -d: -f2)
	local BE_RECURSIVE=$(echo $item| cut -d: -f3)
	local BE_NUM_DAILY=$(echo $item| cut -d: -f4)
	local BE_NUM_WEEKLY=$(echo $item| cut -d: -f5)
	
	local BE_NUM_MONTHLY=$(echo $item| cut -d: -f6)
	echo "NAME: "$BE_NAME""
	echo "DIRECTORY: "$BE_DIRECTORY""
	echo "RECURSIVE: "$BE_RECURSIVE""
	echo "NUM_DAILY: "$BE_NUM_DAILY""
	echo "NUM_WEEKLY: "$BE_NUM_WEEKLY""
	echo "NUM_MONTHLY: "$BE_NUM_MONTHLY""
	echo
done
}


CONFIG_PATH="./backup.conf"

echo "Parsing config file..."

#preserve newlines
IFS=
CONFIG_TEXT=$(cat $CONFIG_PATH)

#remove comments
CONFIG_TEXT=$(echo $CONFIG_TEXT | sed -e 's/#.*//g') 
#remove spaces from variables
CONFIG_TEXT=$(echo $CONFIG_TEXT | sed -e 's/[ \t]=[ \t]/=/g') 
#quote variable values
CONFIG_TEXT=$(echo $CONFIG_TEXT | sed -r -e 's/(=)(.*)/="\2"/g') 
#replace '-' with '_'
CONFIG_TEXT=$(echo $CONFIG_TEXT | sed -r -e 's/-/_/g') 
#extract backup entries from config
BACKUP_ENTRIES_TEXT=($(echo $CONFIG_TEXT | sed -nr '/.*:.*/p'))
#remove backup entries from config
CONFIG_TEXT=$(echo $CONFIG_TEXT | sed -r -e 's/.*:.*//g')

#debug
#echo $CONFIG_TEXT > temp.txt
#echo $BACKUP_ENTRIES_TEXT > btemp.txt

#run config as a script to get variables
eval $CONFIG_TEXT

#print standard variables
echo
echo "printing variable values..."
echo "COMPRESSION: "$COMPRESSION""
echo "E-MAIL: "$E_MAIL""
echo "BACKUP_TARGET: "$BACKUP_TARGET""
echo "TARGET_TYPE: "$TARGET_TYPE""
echo "TARGET_SERVER: "$TARGET_SERVER""
echo "TARGET_FS: "$TARGET_FS""
echo "USER: "$USER""
echo "PASSWORD: "$PASSWORD""

#read the backup entries into an array for parsing
readarray -t BACKUP_ENTRIES_ARRAY <<<$BACKUP_ENTRIES_TEXT
parse_backup_entries