#! /bin/bash

CONFIG_PATH="./backup.conf"

echo "Reading config file"

#preserve newlines
IFS=
CONFIG_TEXT=$(cat $CONFIG_PATH)
#echo $CONFIG_TEXT

#remove comments
CONFIG_TEXT=$(echo $CONFIG_TEXT | sed -e 's/#.*//g') 
#remove spaces from variables
CONFIG_TEXT=$(echo $CONFIG_TEXT | sed -e 's/[ \t]=[ \t]/=/g') 
#quote variable values
CONFIG_TEXT=$(echo $CONFIG_TEXT | sed -r -e 's/(=)(.*)/="\2"/g') 
#replace - with _
CONFIG_TEXT=$(echo $CONFIG_TEXT | sed -r -e 's/-/_/g') 
#extract backup entries from config
BACKUP_ENTRIES_TEXT=$(echo $CONFIG_TEXT | sed -nr '/.*:.*/p')
#remove backup entries from config
CONFIG_TEXT=$(echo $CONFIG_TEXT | sed -r -e 's/.*:.*//g')

#debug
echo $CONFIG_TEXT > temp.txt
echo $BACKUP_ENTRIES_TEXT > btemp.txt

#run config as a script to get variables
eval $CONFIG_TEXT

echo $COMPRESSION